<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dropdown NO 1</name>
   <tag></tag>
   <elementGuidId>89f19b2e-2569-45aa-ad45-6b6a65648e24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.dtr-data > div.dropdown.show > #dropdownMenuLink1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='dropdownMenuLink1'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bd83081b-3e69-4c65-a26c-5f6584cd9bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-primary dropdown-toggle</value>
      <webElementGuid>a0075ab3-ec47-4217-9be0-a7aa2d78afa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>658f8ee0-b3bd-446e-84ea-ff91bebf9594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ebc80b89-a396-452f-b093-a3e3baef9ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdownMenuLink1</value>
      <webElementGuid>e2857f46-eaaf-4905-87eb-a43c828d135e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>21af7e64-d289-430f-b53e-314eee8b1e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>30a92788-1982-4e01-a8b4-a56788f51325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ecca197f-e29a-4833-b300-dcd354c48a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Dropdown
                </value>
      <webElementGuid>d17e828b-4ac3-44fb-b585-00f45dcec5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl_history&quot;)/tbody[1]/tr[@class=&quot;child&quot;]/td[@class=&quot;child&quot;]/ul[@class=&quot;dtr-details&quot;]/li[1]/span[@class=&quot;dtr-data&quot;]/div[@class=&quot;dropdown show&quot;]/a[@id=&quot;dropdownMenuLink1&quot;]</value>
      <webElementGuid>fd58dac8-fcd6-48ab-8d26-885d61ed2a7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='dropdownMenuLink1'])[2]</value>
      <webElementGuid>c0634bd4-032c-475b-b3b8-937c4d3104bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbl_history']/tbody/tr[2]/td/ul/li/span[2]/div/a</value>
      <webElementGuid>6c202def-1ec2-47a8-8222-7ac32f18d4ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Dropdown')])[2]</value>
      <webElementGuid>1e858c20-2065-42bc-af65-8fc88263892a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[2]/following::a[1]</value>
      <webElementGuid>9b3b316b-c5dd-483a-9ece-214992c4a726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show LOG'])[1]/following::a[1]</value>
      <webElementGuid>600443b1-ff12-4b15-a1bd-cd45507c364d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[2]/preceding::a[1]</value>
      <webElementGuid>e2feb5b1-fad7-4e0e-b7a1-68bdea0a2c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show LOG'])[2]/preceding::a[2]</value>
      <webElementGuid>88b07106-3628-401e-9501-22dd8ae65c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[13]</value>
      <webElementGuid>e608b604-4b4c-43c5-a99d-48dab0a66bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/a</value>
      <webElementGuid>9a03a662-eda7-439a-bdcf-e59f003ea469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'dropdownMenuLink1' and (text() = '
                    Dropdown
                ' or . = '
                    Dropdown
                ')]</value>
      <webElementGuid>107da234-ff95-4087-8782-ac12065558bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
