<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__kode_pos_deb</name>
   <tag></tag>
   <elementGuidId>ca849b75-c783-401b-9993-b65448f73f57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kode_pos_deb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kode_pos_deb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24c1b7d9-d590-46c2-912e-17e8fcc612d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kode_pos_deb</value>
      <webElementGuid>3c51b61b-a331-4133-a903-33580d2cb8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kode_pos_deb</value>
      <webElementGuid>68b5198d-6e87-4591-a60f-77cacd87099d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm number_input</value>
      <webElementGuid>b122b658-52c0-492e-83ad-3ac064235430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e17f1180-28d9-41a2-9753-23b4b1d44d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>86cca7d0-5ce3-41a3-be10-d21656bf7bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kode_pos_deb&quot;)</value>
      <webElementGuid>7412ba91-ad99-498e-adf0-4b8e230bd00b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kode_pos_deb']</value>
      <webElementGuid>cf3011df-c2e8-4784-b621-61be4373b208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_identitas_debitur']/div[12]/input</value>
      <webElementGuid>39548ba1-71d7-4a4e-b945-86fc99c7c10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/input</value>
      <webElementGuid>39fa294c-c566-4659-ad5f-827e625dbcf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'kode_pos_deb' and @id = 'kode_pos_deb' and @type = 'text']</value>
      <webElementGuid>8b54ccde-5b4c-4e5c-9111-63568a0f4539</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
