<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__tempat_lahir</name>
   <tag></tag>
   <elementGuidId>c7aa9d1d-43c9-4bd7-8f06-c7f6698b7dde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tempat_lahir</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tempat_lahir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56260be5-c9fe-4ee4-9463-8791ec968aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2c67607c-e365-4396-99db-a520cea94d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tempat_lahir</value>
      <webElementGuid>5fe4787d-53a6-4616-993e-2349365f40be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tempat_lahir</value>
      <webElementGuid>86e9e9d8-728c-41e6-91bd-842a0e7df0f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm alphabet_input</value>
      <webElementGuid>e8acb1f3-0f65-4b0a-8688-a04adaf5a2a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempat_lahir&quot;)</value>
      <webElementGuid>79ce154e-7b91-4c77-822c-6198c8427e94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tempat_lahir']</value>
      <webElementGuid>b9b71329-2f0f-4a33-a329-a8f384d0ab71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_identitas_debitur']/div[16]/input</value>
      <webElementGuid>ebf23999-a740-42f3-83f5-470a197e1a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/input</value>
      <webElementGuid>7a87c784-0bd8-4130-8984-39ff6db81219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tempat_lahir' and @name = 'tempat_lahir']</value>
      <webElementGuid>3332bb25-7d39-4128-9eac-dbef0ad639ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
