<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__debitur_phone_number</name>
   <tag></tag>
   <elementGuidId>4e78d696-0cc9-4669-838b-608d081bbd26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#debitur_phone_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='debitur_phone_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13d67ace-eebd-4ff5-a97f-211535530d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2eb615d2-7fa6-4954-89ec-eb285597d7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>debitur_phone_number</value>
      <webElementGuid>ded7aa49-f9fc-427f-8f02-f2bcae7a44a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>debitur_phone_number</value>
      <webElementGuid>ed560d3b-4d86-48e5-b94f-ffc88d96a26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm phone_number_class number_input</value>
      <webElementGuid>8c48fd91-e7dc-4b5c-84b3-81bc4e085b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;debitur_phone_number&quot;)</value>
      <webElementGuid>eced22e1-0c92-4574-998c-e277b4a74b9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='debitur_phone_number']</value>
      <webElementGuid>46f22e9f-5f1b-47ca-af51-b9ee9096c67d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_phone_number']/div/div/input</value>
      <webElementGuid>6726858f-59ac-49da-bc30-ce99052e384e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/div/input</value>
      <webElementGuid>e583820a-fa4d-4109-ac51-5848643816b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'debitur_phone_number' and @name = 'debitur_phone_number']</value>
      <webElementGuid>324cd28f-fe0b-4763-8278-6717c74b76f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
