<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-- Pilih --_plafon_baru 1</name>
   <tag></tag>
   <elementGuidId>c115e361-e18b-4022-aa67-57af14f9dcbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='plafon_baru[]'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad93f97f-f2eb-4f21-8b8c-fa220a9b6358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ba4907d0-0bbb-4103-9034-0cb6d7e4ba31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>plafon_baru[]</value>
      <webElementGuid>8daddbed-2cce-4915-99cb-b6a1e83d63e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm maskmoney plafon_baru</value>
      <webElementGuid>b7e534d7-7e02-452a-bce6-94599755482b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_fasilitas&quot;)/tbody[1]/tr[@class=&quot;new_fasilitas&quot;]/td[7]/input[@class=&quot;form-control form-control-sm maskmoney plafon_baru&quot;]</value>
      <webElementGuid>c1422de6-3ca0-4214-a8f6-5811f1aea791</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='plafon_baru[]'])[2]</value>
      <webElementGuid>3af7bc90-fd9d-4336-b3f5-cc56f44e8836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_fasilitas']/tbody/tr[2]/td[7]/input</value>
      <webElementGuid>1451aff6-0e1c-4115-a9ef-6b509f19124e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[7]/input</value>
      <webElementGuid>f3cf60c6-efed-43ed-b86c-a0ba06fc6dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'plafon_baru[]']</value>
      <webElementGuid>56e8f4ef-4f06-40f8-a237-04bf41cec11d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
