<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-- Pilih --_plafon_baru 2</name>
   <tag></tag>
   <elementGuidId>aea8df38-9a6f-48c1-86a1-7905901317c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='plafon_baru[]'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6980c2a6-59fe-446f-975e-87cefed0d488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84dbef23-501a-4852-b01f-99ea634533e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>plafon_baru[]</value>
      <webElementGuid>6a83b605-ad80-4f0e-8243-9dd08b11b6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm maskmoney plafon_baru</value>
      <webElementGuid>eae60a0c-ce15-4051-a1f0-6c26e16bb514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_fasilitas&quot;)/tbody[1]/tr[@class=&quot;new_fasilitas&quot;]/td[7]/input[@class=&quot;form-control form-control-sm maskmoney plafon_baru&quot;]</value>
      <webElementGuid>9360fc04-d28a-4bf1-9b7e-656d0b06b0e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='plafon_baru[]'])[2]</value>
      <webElementGuid>1c89d990-9770-498f-9e08-746a1c5eb2be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_fasilitas']/tbody/tr[2]/td[7]/input</value>
      <webElementGuid>5f8e4579-4396-4bde-8ef5-bb0468720197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[7]/input</value>
      <webElementGuid>9541999e-26cb-4e91-bb6d-ef691761d4cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'plafon_baru[]']</value>
      <webElementGuid>fbed91c3-684f-4082-9a7b-15f69841e2ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
