<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__nama</name>
   <tag></tag>
   <elementGuidId>973d6433-1a09-4da9-8c61-5de4c9125f77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nama</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nama']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93a5e470-4a72-4b42-94e5-0b0b02604551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>43bd6317-1ac6-4f75-be81-f6d326676d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama</value>
      <webElementGuid>f42c7c99-f7f0-4556-a9a7-76910ff22e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama</value>
      <webElementGuid>4e9aa8f9-2c3c-49e2-a90c-6dc63955731b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm alphabet_input</value>
      <webElementGuid>72424041-5001-437b-a304-ff87b778abb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nama&quot;)</value>
      <webElementGuid>6bb10bd2-56d2-4fcf-9e70-729dee400c19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nama']</value>
      <webElementGuid>14d496e3-9f7f-4f4b-b334-4b07800222ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_identitas_debitur']/div[8]/input</value>
      <webElementGuid>b4c1323e-28d5-4238-b6c0-fb685184b7a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>e482954e-111e-42ed-9c89-ecde91b39d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nama' and @name = 'nama']</value>
      <webElementGuid>f05d73c8-e080-4d82-a875-5b30f05fbcff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
