<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__kota_deb</name>
   <tag></tag>
   <elementGuidId>4e118c54-321f-4499-bcc8-05a9e029a236</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kota_deb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kota_deb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61adef89-f523-4f78-b03d-bf3c8ad88068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kota_deb</value>
      <webElementGuid>f96aee39-c648-4464-ba12-a8581b70a926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kota_deb</value>
      <webElementGuid>7d0ccbda-74e7-43a3-b504-2cfdb004a067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm alphabet_input</value>
      <webElementGuid>5f8ecf7b-80a7-45c3-91be-d9265a28c4ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>76932294-4f07-4367-aa20-9fda324607aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kota_deb&quot;)</value>
      <webElementGuid>526117d0-ace1-4fae-b822-b238b8a7192f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kota_deb']</value>
      <webElementGuid>4883e689-1abd-4702-9aaf-c2a29f8f7280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_identitas_debitur']/div[11]/input</value>
      <webElementGuid>98120649-e246-4b4e-9e90-fdd4453dc82b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/input</value>
      <webElementGuid>bc80f375-8325-4421-9c84-5279b68f28d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'kota_deb' and @id = 'kota_deb' and @type = 'text']</value>
      <webElementGuid>576204a2-f26e-4f1a-9545-5a088e7d0a14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
