<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Individu  Perorangan_nik_akta_dhnbi</name>
   <tag></tag>
   <elementGuidId>a153e7ea-6338-4648-bf2e-330189f7507e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nik_akta_dhnbi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nik_akta_dhnbi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eeb23614-4bac-4ce7-a2e1-1a0e9948b46d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>af26b1ea-1cca-4482-b4d0-3373bfffbee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nik_akta_dhnbi</value>
      <webElementGuid>4b0d9dac-5c44-4950-babd-8a6bca4ac480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nik_akta_dhnbi</value>
      <webElementGuid>a15aa56b-f456-4376-9ef3-da62a1b796df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control number_input</value>
      <webElementGuid>cf2f81dd-b834-4879-b136-eff5a877226c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Check NIK</value>
      <webElementGuid>dc6b2719-9357-4072-a876-786546693ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>c714e5c1-8de5-4813-b0fa-538fde9121e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nik_akta_dhnbi&quot;)</value>
      <webElementGuid>26f54817-06ee-4739-b284-270f813277fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nik_akta_dhnbi']</value>
      <webElementGuid>e733344d-6a43-42ee-af6b-11533175e38f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_check_dhnbi']/div/div/div/input</value>
      <webElementGuid>4b231cda-139d-4b96-8533-ebf63b81f455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>ef52a8d6-92a0-41a7-a884-3608c2559dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nik_akta_dhnbi' and @name = 'nik_akta_dhnbi' and @placeholder = 'Check NIK']</value>
      <webElementGuid>5beac434-5e3b-45d2-ab20-ace46acf053e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
