<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__nama_ibu_deb</name>
   <tag></tag>
   <elementGuidId>b8737c86-ee2f-4b9c-b91c-82b9b1e99598</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nama_ibu_deb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nama_ibu_deb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b66ee75-ad11-4561-9913-33e723ed45b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_ibu_deb</value>
      <webElementGuid>35d35b73-ac3c-464a-b3a9-06c4bbdc958c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama_ibu_deb</value>
      <webElementGuid>ca1db12d-6ff8-4644-a573-bafe0e377ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm alphabet_input</value>
      <webElementGuid>3cc7ac22-cbfa-4a53-8824-a0da5c80ae6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aa04b5fb-d30c-4a91-94ce-eeb2ef6d0256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nama_ibu_deb&quot;)</value>
      <webElementGuid>0777d306-d335-452d-a74d-b44d28d1d12d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nama_ibu_deb']</value>
      <webElementGuid>da34a97a-5f07-4176-90bd-5d1d4a69f8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_nama_ibu_deb']/input</value>
      <webElementGuid>7350b900-9a22-45d0-9ccc-24481087fc87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/input</value>
      <webElementGuid>bbed6490-23d2-41df-97ca-dfb52adbd37d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nama_ibu_deb' and @id = 'nama_ibu_deb' and @type = 'text']</value>
      <webElementGuid>90e85602-7097-4a2b-8464-07fb05bc5236</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
