<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__tgl_lahir_akta</name>
   <tag></tag>
   <elementGuidId>b6a8d2cc-dd46-4a03-a454-91f6a78e2265</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tgl_lahir_akta</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tgl_lahir_akta']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f05f861c-cf08-449d-962f-ddea151c44dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>37eba6c0-2ebb-4332-96ad-1d355c1a6cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tgl_lahir_akta</value>
      <webElementGuid>118df467-d8c3-49f1-8ef4-dd09a8cdaddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tgl_lahir_akta</value>
      <webElementGuid>7f1f54d7-c460-460f-9b9c-b37bc934e1ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>1f482b64-f362-40fb-a70f-fb7e1e5bf04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-inputmask-alias</name>
      <type>Main</type>
      <value>datetime</value>
      <webElementGuid>39e96646-4c09-4320-b7eb-1612b072f3db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-inputmask-inputformat</name>
      <type>Main</type>
      <value>dd-mm-yyyy</value>
      <webElementGuid>9126b29c-bc12-48cb-865f-36cbf7df226a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-inputmask-placeholder</name>
      <type>Main</type>
      <value>dd-mm-yyyy</value>
      <webElementGuid>b1a6af34-e8c4-4661-8321-8fb73026da74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd-mm-yyyy</value>
      <webElementGuid>3cf17ee4-7fc4-492f-ba89-e20edba77da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>5be7a399-7841-4883-a59f-85a49c4e5652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tgl_lahir_akta&quot;)</value>
      <webElementGuid>270c0465-e93c-429d-be1b-c864f144cecb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tgl_lahir_akta']</value>
      <webElementGuid>b8acbd83-44d8-4a3f-901c-7f54bdb6d578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_identitas_debitur']/div[15]/div/input</value>
      <webElementGuid>6f3e00ad-09a9-4e6e-9fb2-7507e804a8bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/input</value>
      <webElementGuid>6614a088-2151-4c06-aebb-a90cfe2512c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tgl_lahir_akta' and @name = 'tgl_lahir_akta' and @placeholder = 'dd-mm-yyyy']</value>
      <webElementGuid>1f1d0e0d-c6ca-4c03-a810-4334de2dd5a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
