<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Tunai</name>
   <tag></tag>
   <elementGuidId>aef232c5-4c1a-4479-a9c9-c5bd1191ed8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form_agunan']/div/div/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>15362d34-15a2-4dcf-9e4c-f75fabf120b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>checkboxPrimary2</value>
      <webElementGuid>8dcd1ebf-ab46-4461-85d2-7370fe94980d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tunai</value>
      <webElementGuid>cd365c23-805d-48be-a758-474e48923f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_agunan&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;p-2 border rounded column-checker&quot;]/div[@class=&quot;icheck-primary&quot;]/label[1]</value>
      <webElementGuid>d2ed3439-c04f-4e98-8ba8-72d7bbb8136b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_agunan']/div/div/div[2]/label</value>
      <webElementGuid>d0a5fef1-c7d0-468f-b78b-8eb09967e3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fixed Asset'])[1]/following::label[1]</value>
      <webElementGuid>eb2e7ed7-d6fb-46b7-8b45-1c1b39e8f6f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Agunan'])[1]/following::label[2]</value>
      <webElementGuid>2c8777f2-f916-4f34-99de-384d72de5da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back To Back'])[1]/preceding::label[1]</value>
      <webElementGuid>300feae8-b3de-43cf-afea-467569ffb5a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penjamin Deposito'])[1]/preceding::label[2]</value>
      <webElementGuid>04f3abcb-3ee0-4486-b24b-109f232e0459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tunai']/parent::*</value>
      <webElementGuid>23d1898e-63a8-4461-87b9-d37068aa9803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/form/div/div/div[2]/label</value>
      <webElementGuid>2de2d457-a46b-4f26-b792-4796c9470844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Tunai' or . = 'Tunai')]</value>
      <webElementGuid>f8e6b2ca-701a-4207-86ae-9344f41a4f75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
