<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Penjamin Deposito</name>
   <tag></tag>
   <elementGuidId>e6f8d90b-9a04-4bcf-b337-cbf0a0e74db0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PJD > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PJD']/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>afddcd29-c320-446d-800b-1a62f701bf3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio_PJD</value>
      <webElementGuid>748bb3fb-a312-4ad8-991b-a8e4cf38d591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Penjamin Deposito</value>
      <webElementGuid>049adaaa-5a26-4dad-8d54-ba8d98984b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PJD&quot;)/label[1]</value>
      <webElementGuid>a20f9ead-8205-4ce9-9687-ca75c53e5771</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PJD']/label</value>
      <webElementGuid>2471ec47-3814-4b8c-9655-ccd0ba878592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back To Back'])[1]/following::label[1]</value>
      <webElementGuid>7ae78a5d-0835-4e3e-98a4-922546faf99a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tunai'])[1]/following::label[2]</value>
      <webElementGuid>ba49efff-4262-4a8f-b81e-f232ec9eb814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agunan Tunai'])[1]/preceding::label[1]</value>
      <webElementGuid>b0672bb2-d09b-4785-844e-06dcfea7251e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ORI'])[1]/preceding::label[2]</value>
      <webElementGuid>12326b84-ab35-4adc-a716-304c8620bb67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Penjamin Deposito']/parent::*</value>
      <webElementGuid>0e0293b6-b1b4-4ed1-a3fa-9e7bf2bf535f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div[2]/label</value>
      <webElementGuid>d1a51751-e35b-416b-9ed5-90ae608ac9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Penjamin Deposito' or . = 'Penjamin Deposito')]</value>
      <webElementGuid>abfb5d7d-21fa-468c-90cb-819181c6f914</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
