<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-- Pilih -- DOKUMEN IDENTITAS</name>
   <tag></tag>
   <elementGuidId>24d71580-f299-4a43-b868-b47becb6d1c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-jenis_dok_identitas-vw-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-jenis_dok_identitas-vw-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f493f1d2-55f8-4747-a7d4-79bbe80cad61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>2cdf1fcf-ae60-4710-ad18-64b5d9b87693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-jenis_dok_identitas-vw-container</value>
      <webElementGuid>27c3fff0-2519-47b4-99fa-930cddae9a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>986e305f-9fa5-4c38-bb00-ac08508d5c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>75d0ece8-6f5f-4650-96f5-5852055b41e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-- Pilih --</value>
      <webElementGuid>a2006e20-2fdc-413f-8c33-d1ab0b14c403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih --</value>
      <webElementGuid>4765bd3d-a74f-4827-a4f5-53596b9c50fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-jenis_dok_identitas-vw-container&quot;)</value>
      <webElementGuid>2b6ff250-bcd1-45a2-8eb4-5f9d9a8fae61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-jenis_dok_identitas-vw-container']</value>
      <webElementGuid>cdecdfed-fc0a-41d8-ab22-3e7c60ee8ecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_lampiran_debitur']/div/div/div/div/span/span/span/span</value>
      <webElementGuid>7702055d-ba5d-4ac4-a68a-4f2f513d1fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[24]/following::span[4]</value>
      <webElementGuid>1d124700-8df8-40bb-adc1-442f12cb7a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[1]/preceding::span[3]</value>
      <webElementGuid>206a2fd7-3acf-4bba-8613-6f3c3a58930f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload'])[1]/preceding::span[3]</value>
      <webElementGuid>af0064d8-1c8f-4bc1-b077-e49d4275de5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/span/span/span/span</value>
      <webElementGuid>e028f4cd-0de5-4c35-b38c-cbd0a597c463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-jenis_dok_identitas-vw-container' and @title = '-- Pilih --' and (text() = '-- Pilih --' or . = '-- Pilih --')]</value>
      <webElementGuid>322da411-e4a4-46b1-9a8d-4f136ed3fbd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
