<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-- Pilih -- SEKOM</name>
   <tag></tag>
   <elementGuidId>91aa8bac-1b50-4054-a8fb-eae1945a41b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-sektor_ekonomi-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-sektor_ekonomi-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4b201ebe-c9ea-40dc-865d-d0a0efa1b5aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>2f193138-86da-48a6-8ad6-d9f0a09d2f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-sektor_ekonomi-container</value>
      <webElementGuid>9fa19af1-ff35-454e-8cd0-60675884d865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>deb82f69-9d85-466b-a09b-190dc4e6de9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5fee9635-8ef7-4d01-8ea5-b175c616e5bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> -- Pilih -- </value>
      <webElementGuid>1e21e531-5da3-43b2-8a63-20b395210799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> -- Pilih -- </value>
      <webElementGuid>e13c6bb1-02d9-439f-bf42-b705155f3edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-sektor_ekonomi-container&quot;)</value>
      <webElementGuid>e233bdb4-9154-48c5-927d-88ca7ac1ce00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-sektor_ekonomi-container']</value>
      <webElementGuid>20526393-5887-468d-b51b-0ae55ecc3742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_identitas_debitur']/div[21]/span/span/span/span</value>
      <webElementGuid>3840c1a4-1c3d-4bf5-b708-25c04174c236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[15]/following::span[4]</value>
      <webElementGuid>9712ef26-9a24-48d7-8e6d-334277cc1d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[16]/preceding::span[3]</value>
      <webElementGuid>97f3b4ab-1b65-4728-ae23-9af4b3a2824c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/span/span/span/span</value>
      <webElementGuid>e7b7b3ce-2faa-4b9c-8de6-46c80bccc0b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-sektor_ekonomi-container' and @title = ' -- Pilih -- ' and (text() = ' -- Pilih -- ' or . = ' -- Pilih -- ')]</value>
      <webElementGuid>add62cd7-2e21-44b1-8027-05e137c84870</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
