<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-- Pilih -- SEGMENTASI</name>
   <tag></tag>
   <elementGuidId>539c91d9-05b1-4c09-ba52-2f967451d2e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-segment_deb-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-segment_deb-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c458eec2-d619-4ec3-910a-2de976385604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>dfbf8ccf-51f2-431c-8139-4a40160b886c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-segment_deb-container</value>
      <webElementGuid>880f5530-d2ac-4f5d-8272-d338cdbe1029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>59f91f5d-a856-4707-abac-ba19dbd87e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4097bd6c-ac33-4a0d-8ddd-fdfa74db6b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> -- Pilih -- </value>
      <webElementGuid>623f3274-db6d-4faa-9f41-392513b33298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> -- Pilih -- </value>
      <webElementGuid>017f29a6-b10c-4718-84d8-e6642a4fa046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-segment_deb-container&quot;)</value>
      <webElementGuid>f3d7077b-4dde-436e-b353-4bdbcaa8e607</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-segment_deb-container']</value>
      <webElementGuid>5e388446-b9cd-4ef8-b9fc-46106b778b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_identitas_debitur']/div[25]/span/span/span/span</value>
      <webElementGuid>038d11f5-4d6f-40fc-9d62-2ad1dad3ab80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[19]/following::span[4]</value>
      <webElementGuid>64f86bbd-a038-490b-8216-00a19a3b492c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[20]/preceding::span[3]</value>
      <webElementGuid>b301d23e-23a6-4f9d-a652-39899807c78c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[25]/span/span/span/span</value>
      <webElementGuid>f7e96d29-1d33-4446-bad9-222b15a545f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-segment_deb-container' and @title = ' -- Pilih -- ' and (text() = ' -- Pilih -- ' or . = ' -- Pilih -- ')]</value>
      <webElementGuid>df139d7c-59eb-421f-9cc6-f56310af7ac4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
