<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-- Pilih -- BIDANG USAHA</name>
   <tag></tag>
   <elementGuidId>3cd08bcb-78d4-4264-a7f7-a3f606d42014</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-bidang_usaha-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-bidang_usaha-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bc37f244-d8e1-4714-a986-2b70b8553f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>63dc1a65-f483-41cf-ac53-64340fb5ef82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-bidang_usaha-container</value>
      <webElementGuid>e23d335a-d8f7-41b3-b7d8-30bca17e47b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>d5741b85-c1cb-40a3-b7ce-51173200ab12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7126681f-90cd-455c-837a-0de93d4069de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> -- Pilih -- </value>
      <webElementGuid>1cb7c51c-f8d4-4e42-add1-5fa936936cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> -- Pilih -- </value>
      <webElementGuid>3b3aa63e-0205-47cd-a0f4-02a6c88ffff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-bidang_usaha-container&quot;)</value>
      <webElementGuid>f61e9686-e5f3-44b8-bba9-0e6e09a43bda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-bidang_usaha-container']</value>
      <webElementGuid>5c77025c-89f2-4664-910b-9ca15c03b019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_identitas_debitur']/div[28]/span/span/span/span</value>
      <webElementGuid>8139f9ca-63ff-4304-90bf-a50fcbd21b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[21]/following::span[4]</value>
      <webElementGuid>a3e271c8-dcae-48de-a636-2036f168709a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agunan'])[1]/preceding::span[3]</value>
      <webElementGuid>48af1e16-3886-4991-9d17-7f464236ca8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Agunan'])[1]/preceding::span[3]</value>
      <webElementGuid>ee7937ec-913c-4d38-8c18-a3b4c23f7f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/span/span/span/span</value>
      <webElementGuid>e9592658-1cb5-4b34-8198-fdf9de36e162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-bidang_usaha-container' and @title = ' -- Pilih -- ' and (text() = ' -- Pilih -- ' or . = ' -- Pilih -- ')]</value>
      <webElementGuid>876c2506-0844-424e-b474-00798cd144d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
