<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Catatan Pengajuan_catatan_crm CATATAN</name>
   <tag></tag>
   <elementGuidId>68069aad-50f0-4dfe-8533-77c5d5c25a3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#catatan_crm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='catatan_crm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>850d780e-0640-484c-bbb5-b5ca760d7ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>catatan_crm</value>
      <webElementGuid>f0117a51-b2a4-478f-95b9-621549976ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>catatan_crm</value>
      <webElementGuid>677dce49-3209-4e57-9497-40e76e6c6dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>16233e7e-d151-4e48-98d5-a268467c3a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>d77b9ebb-06cc-49d9-a5e5-a793fabc74fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;catatan_crm&quot;)</value>
      <webElementGuid>b58fd8fd-9c3a-417d-b1b5-dd3bbd14461a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='catatan_crm']</value>
      <webElementGuid>8a6204e1-bf7b-4515-ab6a-cbb4915ac82d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_identitas_debitur']/div[27]/div/textarea</value>
      <webElementGuid>d8b79ad4-26bf-4544-9804-417e04e161ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div/textarea</value>
      <webElementGuid>e3e8723a-7b14-4346-9f39-0a4fe7f42b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'catatan_crm' and @id = 'catatan_crm']</value>
      <webElementGuid>597f9235-ad1a-4f31-a66f-98cd92ee9e75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
