<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__alamat</name>
   <tag></tag>
   <elementGuidId>5db6d1e5-7eb8-41f5-a91d-e4dc7466f9d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alamat</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='alamat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>17f507b9-3102-46fc-b851-04545f70ae5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>84f50ce1-df9a-4f5c-9e16-dd15658702b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>alamat</value>
      <webElementGuid>45af68af-658c-424b-b6b9-657bd34b5cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alamat</value>
      <webElementGuid>03e3dfce-2e96-45ad-9e3c-97dc5066122f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>c9fe002b-f427-49dd-8b93-d5f543f2a626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cc2bfae4-acf7-4de7-82d0-1c3d8adad068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alamat&quot;)</value>
      <webElementGuid>14adfaab-1fba-49c7-9114-6212bc54d0dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='alamat']</value>
      <webElementGuid>105e2559-2c7d-47dc-9fb2-b364bc925ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_identitas_debitur']/div[10]/textarea</value>
      <webElementGuid>5f371ce2-bc3f-4fb1-a27e-50f54bf962ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>4cbf69e6-7999-4d4a-b8a0-b213aa38d534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'alamat' and @id = 'alamat' and @type = 'text']</value>
      <webElementGuid>5056bde7-c756-4462-9af4-b968bf711813</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
