<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>small_Login</name>
   <tag></tag>
   <elementGuidId>52ae99cc-c2e9-4944-9a4f-d5a97e371a93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>small.login_link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='navigation']/ul/li/a/small</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>75e8caab-ab81-46f6-80c8-308b438fe6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login_link</value>
      <webElementGuid>cbbacde6-dd9c-4fae-8557-7049f3b4058c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>6b2906ee-f33e-4694-afe2-2e7c9cc96263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navigation&quot;)/ul[@class=&quot;user-menu nav nav-tabs nav-stacked main-menu&quot;]/li[@class=&quot;mm-profile user-link&quot;]/a[1]/small[@class=&quot;login_link&quot;]</value>
      <webElementGuid>eaa8a41a-25a1-4865-b1e8-a26a18b1f501</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navigation']/ul/li/a/small</value>
      <webElementGuid>4a344ed1-562d-46e6-b2d3-4c0fbcf2e569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visitor'])[1]/following::small[1]</value>
      <webElementGuid>f77788e3-a4a4-4b4e-be6a-62009b6857bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::small[1]</value>
      <webElementGuid>cd528666-eab0-486e-bd2d-07923c2c450d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parameter'])[1]/preceding::small[1]</value>
      <webElementGuid>ca4ebbd2-ed89-40d3-a241-551e72261dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parameter BWMK Regional'])[1]/preceding::small[1]</value>
      <webElementGuid>d119377a-82bf-428c-a214-d046ea57fe56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//small</value>
      <webElementGuid>cfb06f63-6c34-4306-9805-6c6f54933293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>b3ef2730-8982-41aa-beee-593a82c3e520</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
