<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Analisa</name>
   <tag></tag>
   <elementGuidId>718baa44-b107-4aab-b099-c16e29bb7599</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='dtl_ay_individu']/tbody/tr[4]/td[6]/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>153dc94e-89cd-49a2-8605-ba974c4ba174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>ay_individu1?_mode=edit&amp;id=00187%2FCIA%2F810%2F2023&amp;name=KATALON+J&amp;inputTgl=2023-10-30&amp;regional=REGIONAL+JAKARTA+I</value>
      <webElementGuid>14d99938-6def-4e2f-aef1-359c46308876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>0d758cb5-9271-4a6f-af9a-608a619b1011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Analisa</value>
      <webElementGuid>6910dc83-1ef5-4aaa-9203-d6fec8f36274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dtl_ay_individu&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[@class=&quot;row_action footable-visible&quot;]/span[@class=&quot;row_action_inner&quot;]/a[1]</value>
      <webElementGuid>e4fcb22c-de6b-43f4-9091-679b991d331f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dtl_ay_individu']/tbody/tr[4]/td[6]/span/a</value>
      <webElementGuid>1fa02108-6efc-426b-9eae-5ad325a73614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Analisa')])[5]</value>
      <webElementGuid>30fd3c77-9328-48db-999b-8ed8abcaf709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ktp'])[3]/following::a[1]</value>
      <webElementGuid>f1d3b261-e94b-4b31-bc42-ba020f19b4ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[6]/following::a[1]</value>
      <webElementGuid>1fb7bfb7-98c3-425d-a4e5-4ccf37b14903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CSV'])[1]/preceding::a[1]</value>
      <webElementGuid>0baa3c7a-0085-4a25-ac68-80634e7fa97b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'ay_individu1?_mode=edit&amp;id=00187%2FCIA%2F810%2F2023&amp;name=KATALON+J&amp;inputTgl=2023-10-30&amp;regional=REGIONAL+JAKARTA+I')]</value>
      <webElementGuid>3d76ddee-77ae-4784-a2b3-d96508f10d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[6]/span/a</value>
      <webElementGuid>739765ec-19f7-4736-8835-ca3910383636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'ay_individu1?_mode=edit&amp;id=00187%2FCIA%2F810%2F2023&amp;name=KATALON+J&amp;inputTgl=2023-10-30&amp;regional=REGIONAL+JAKARTA+I' and (text() = 'Analisa' or . = 'Analisa')]</value>
      <webElementGuid>f72eec19-9571-44eb-9a38-d3fa61342cb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
