<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Individu  Perorangan_nik_akta_dhnbi</name>
   <tag></tag>
   <elementGuidId>914c29f1-b8c3-4153-a9a6-eb82aa06ac4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nik_akta_dhnbi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nik_akta_dhnbi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4301509-e375-42b2-9543-69fb3255109e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cadb9db1-2b8b-44cf-a718-156d96a965cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nik_akta_dhnbi</value>
      <webElementGuid>8dccec35-5e71-4589-8b3f-895c98df8c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nik_akta_dhnbi</value>
      <webElementGuid>d11dc056-cfb4-40f6-b66e-e6e8dfdf19eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control number_input</value>
      <webElementGuid>23696d65-ced7-4048-a629-a4ec2e0c01d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Check NIK</value>
      <webElementGuid>5fc4c9e9-e2de-497d-b052-0ef1d30fcac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>39db6777-606a-469f-8def-b024cdf3fcfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nik_akta_dhnbi&quot;)</value>
      <webElementGuid>568c66b8-6e93-4a52-911c-e296b4bc0cc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nik_akta_dhnbi']</value>
      <webElementGuid>6e3a6ddc-d53b-432a-a868-ccd71fd55f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_check_dhnbi']/div/div/div/input</value>
      <webElementGuid>853b254f-bbda-4547-b93c-ae9e09a5c0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>036b5c73-edad-412f-8ba9-0ce8e2ac61b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nik_akta_dhnbi' and @name = 'nik_akta_dhnbi' and @placeholder = 'Check NIK']</value>
      <webElementGuid>b490c580-bc45-4d32-802b-e15431f29dc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
