<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__kode_pos_deb</name>
   <tag></tag>
   <elementGuidId>c0b90b4e-827d-4edd-8d9f-ab9a9a5931e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kode_pos_deb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kode_pos_deb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34541ae5-b297-438a-88df-66284d3e4d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kode_pos_deb</value>
      <webElementGuid>7c552c5b-28fd-466a-a524-988a8780b2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kode_pos_deb</value>
      <webElementGuid>84f0eac5-bccb-42f0-b41a-0afff9f54b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm number_input</value>
      <webElementGuid>624f1912-4b1b-433a-b241-45d3a64db830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6ae68d81-efb8-4491-abe2-c68478c3080b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>79c0ff57-f6dc-4c23-bac3-18a3dea22518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kode_pos_deb&quot;)</value>
      <webElementGuid>4c546c0f-43cf-480f-a29b-e841839324e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kode_pos_deb']</value>
      <webElementGuid>a484ebb6-40da-4a1c-8f31-dc216b248017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_identitas_debitur']/div[12]/input</value>
      <webElementGuid>8cfa0245-a5da-4486-99a7-1c4a8fdaee92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/input</value>
      <webElementGuid>b29a72be-7e71-452d-96a2-9ad5edcb3d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'kode_pos_deb' and @id = 'kode_pos_deb' and @type = 'text']</value>
      <webElementGuid>633ba7df-dd14-4251-8286-b522d2b21082</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
