<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__kota_deb</name>
   <tag></tag>
   <elementGuidId>7209cc89-24ce-4d5d-ab3a-e239997ee928</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kota_deb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kota_deb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e15914b1-691a-4aea-8d68-0f6e492df631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kota_deb</value>
      <webElementGuid>f661222d-4632-44c0-941a-eb77d7422e9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kota_deb</value>
      <webElementGuid>632d837e-3197-4034-bccf-63775bec3f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm alphabet_input</value>
      <webElementGuid>83a6614e-078b-4fab-85e8-dcf7e7275159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d80c628b-e78b-44cf-943a-ffe850592109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kota_deb&quot;)</value>
      <webElementGuid>96609d6a-8f0a-4f83-9d35-76e1f9057b71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kota_deb']</value>
      <webElementGuid>1adf6fdf-704b-4382-9a3d-c7875e2c20ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_identitas_debitur']/div[11]/input</value>
      <webElementGuid>6372e195-5310-4d5c-b318-c25b6032321e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/input</value>
      <webElementGuid>69c12ac9-d2ce-4ece-9214-520a3bdcd7e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'kota_deb' and @id = 'kota_deb' and @type = 'text']</value>
      <webElementGuid>5d294b96-3fd7-4116-8b47-e51aa34906b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
