<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__status_marital</name>
   <tag></tag>
   <elementGuidId>9055cd05-cdda-4df7-8baa-2f3d1f2783ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='status_marital']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#status_marital</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ea12adf-48f8-4e82-bd21-4e25c08c1f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>status_marital</value>
      <webElementGuid>0df47378-876a-4aa4-a384-d280ea7c65b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status_marital</value>
      <webElementGuid>a7f5f661-3e71-4e74-985b-e0c7bb3a3ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield_34191208</value>
      <webElementGuid>3ba9b306-7ac9-4a0b-b1b9-757dc27344e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9c3430d5-ce07-48fe-b042-4f98a3fe2447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;status_marital&quot;)</value>
      <webElementGuid>8fa1dc75-6c2b-464f-b391-365f92827c0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='status_marital']</value>
      <webElementGuid>7546d37a-07dd-4502-8dc1-2a005223f8d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section3']/div[3]/div[6]/input</value>
      <webElementGuid>b6990aa3-6c5a-4880-b68c-23d358e2c19e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[6]/input</value>
      <webElementGuid>7900238e-cf0e-4c1a-be04-1893a9ab5143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'status_marital' and @name = 'status_marital' and @type = 'text']</value>
      <webElementGuid>a6ceec02-82e1-4911-8a43-57cc6449eef6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
