<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__no_kk</name>
   <tag></tag>
   <elementGuidId>1f107f57-eb48-4a2e-88f2-cfe3a9998719</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='no_kk']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#no_kk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4cbc6e4-1e53-4dbc-8b6a-df9318566d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>no_kk</value>
      <webElementGuid>9bb1d792-b64d-49b7-af3e-5f393dba4639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>no_kk</value>
      <webElementGuid>3fa5bb5f-94c9-412a-985d-44836f9f1e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield_34191209</value>
      <webElementGuid>a86dbda8-bcf1-4eda-8d4b-a13eb43150b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4511f9ae-3525-4776-816d-5b6f68fe2a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;no_kk&quot;)</value>
      <webElementGuid>819f8414-5e34-416c-b512-6ecdd3b8da98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='no_kk']</value>
      <webElementGuid>f2943fc5-d3f6-4ddb-99e5-582c76f9114f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section3']/div[3]/div[7]/input</value>
      <webElementGuid>a1586aaf-b8fd-4a65-974c-813df0ffbf65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>c347613e-8cfd-4b7a-a635-8028b643168e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'no_kk' and @name = 'no_kk' and @type = 'text']</value>
      <webElementGuid>320a3fbb-e6f7-4bd7-ab36-48d450dd1ee2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
