<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__pekerjaan</name>
   <tag></tag>
   <elementGuidId>3c1f786f-bcb2-4d1e-a763-e6f9a7506097</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pekerjaan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pekerjaan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08deb203-8a3d-48dc-b05c-f75dfa03e437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pekerjaan</value>
      <webElementGuid>62199e78-584d-42b1-87bb-d73c1b0907d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pekerjaan</value>
      <webElementGuid>d8e1d7c2-1420-48ee-8e80-60c603f91b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield_34191206</value>
      <webElementGuid>6bf76106-ae6e-495c-9f68-2d6cae110a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>da9d3433-003f-4f78-bb9c-be716f55ec7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pekerjaan&quot;)</value>
      <webElementGuid>4789d673-0d10-4dce-821e-4c7fa3745fc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pekerjaan']</value>
      <webElementGuid>eab3568b-7f7f-4423-ae96-dd4312b5b1a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section3']/div[3]/div[4]/input</value>
      <webElementGuid>5bbe5224-58d8-4c82-90ea-f3120986059c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/input</value>
      <webElementGuid>69340c8c-c37f-4074-9c90-d8e26ccd3a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pekerjaan' and @name = 'pekerjaan' and @type = 'text']</value>
      <webElementGuid>fef8bfb4-2709-4e2b-9c4e-202dce40b64c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
