<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__domisili_iu</name>
   <tag></tag>
   <elementGuidId>b495b996-689c-4d59-a919-2bda0ffb3cee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='domisili_iu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#domisili_iu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c17c1088-6cdc-4d16-8ce3-40abde5500ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>domisili_iu</value>
      <webElementGuid>822bcbf4-0a2d-4eb1-a4de-7ae56db86ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>domisili_iu</value>
      <webElementGuid>2693d587-8c85-4a9c-828c-c752bfc1977e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield_34191246</value>
      <webElementGuid>4d8da13f-27cb-4479-9875-bfc7049d627b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0f27e9f1-33f6-4288-afe9-51a1e5017f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;domisili_iu&quot;)</value>
      <webElementGuid>62f1eb4d-4062-4d53-9b5e-10f11aad2e1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='domisili_iu']</value>
      <webElementGuid>03601cd9-f6c5-47a8-98b8-5ef35a1b323e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section5']/div[3]/div[4]/input</value>
      <webElementGuid>35eadc34-a41e-4e2a-be85-66baffa7f5ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div[4]/input</value>
      <webElementGuid>bd63d4eb-f535-47b9-a1ba-c3df04cf126a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'domisili_iu' and @name = 'domisili_iu' and @type = 'text']</value>
      <webElementGuid>742ddb3e-0165-4834-99e0-3b920d63bb2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
