<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__no_kk_pj</name>
   <tag></tag>
   <elementGuidId>a2f5c707-4d00-4a04-807a-22b8cf8fe8af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='no_kk_pj']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#no_kk_pj</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc144d45-6717-4c36-be8d-e79369699362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>no_kk_pj</value>
      <webElementGuid>1089b1df-4b3b-42ae-93bf-ce9bf5ec267e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>no_kk_pj</value>
      <webElementGuid>b75fbbb1-2289-4e44-9722-7962b2f1adba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield_34191231</value>
      <webElementGuid>1cc49632-7f59-4a30-9590-290562762402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>962085ac-46ae-4d84-9c44-742b709140b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;no_kk_pj&quot;)</value>
      <webElementGuid>4ae9fe59-1678-43b0-8196-6ef265da5abd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='no_kk_pj']</value>
      <webElementGuid>f1bbad0d-b637-4a01-bb54-26d4c4062479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section4']/div[3]/div[7]/input</value>
      <webElementGuid>817241ad-797c-416a-8d05-a324ae7e861a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div[7]/input</value>
      <webElementGuid>24fe908c-5a21-429c-bab3-afc72799e248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'no_kk_pj' and @name = 'no_kk_pj' and @type = 'text']</value>
      <webElementGuid>ba03fcba-9662-43c1-a909-aaf0ed2f54d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
