<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__tgl_lahir_akta_pj</name>
   <tag></tag>
   <elementGuidId>f7c7e896-062b-4c8b-b52a-7c124a15c8e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tgl_lahir_akta_pj_34191226']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tgl_lahir_akta_pj_34191226</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c3cdbc8-070c-4147-89f8-22c904f1a09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tgl_lahir_akta_pj_34191226</value>
      <webElementGuid>3a104dd0-5e03-44e8-8f6c-ba13dc403c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tgl_lahir_akta_pj</value>
      <webElementGuid>883b75a6-00ab-4246-bced-499615c19d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>28899ac9-ab80-4893-82ff-ec4a5759d03a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tgl_lahir_akta_pj  hasDatepicker focus</value>
      <webElementGuid>81d658fd-f84b-41d3-b4f7-b6fca179a633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD-MM-YYYY</value>
      <webElementGuid>546674d6-9324-4b8b-bcfd-8cfc336b056f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tgl_lahir_akta_pj_34191226&quot;)</value>
      <webElementGuid>b46e87a8-6eb9-4bd5-899d-fd168961dcd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tgl_lahir_akta_pj_34191226']</value>
      <webElementGuid>acdcebce-dbd7-409b-8998-5a7fbfbfdba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section4']/div[3]/div[2]/input</value>
      <webElementGuid>cdb0eef9-42d3-4a80-a28e-a0cbe90ede09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div[2]/input</value>
      <webElementGuid>49be080e-9c4e-4a12-b192-ffc1b70ddc1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tgl_lahir_akta_pj_34191226' and @name = 'tgl_lahir_akta_pj' and @type = 'text' and @placeholder = 'DD-MM-YYYY']</value>
      <webElementGuid>0942f02d-f869-4b80-8989-be2046eaf7a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
