<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__npwp_pj</name>
   <tag></tag>
   <elementGuidId>950af0da-63b5-4936-8eff-4a29a4c9d2d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='npwp_pj']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#npwp_pj</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15800724-c021-4cf5-aaa9-71e532a1a01f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>npwp_pj</value>
      <webElementGuid>df8d8486-cf49-439b-8ebb-d842796caffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>npwp_pj</value>
      <webElementGuid>7647f050-0519-450a-b863-908f7e968a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield_34191233</value>
      <webElementGuid>f33ae750-6994-48a9-b7aa-e92e94b0d222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7dc76f14-a97c-4eba-86a8-abaefcfa170a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;npwp_pj&quot;)</value>
      <webElementGuid>0cfdc7ab-e69d-41d4-9a54-92822cddf0e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='npwp_pj']</value>
      <webElementGuid>60c57f83-3d9b-4336-8b63-a507e73df8ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section4']/div[3]/div[9]/input</value>
      <webElementGuid>4199ac58-5a4c-4d85-8c5b-f951e06576e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div[9]/input</value>
      <webElementGuid>e017f3b7-537c-4c8b-b65f-d6141e1986dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'npwp_pj' and @name = 'npwp_pj' and @type = 'text']</value>
      <webElementGuid>551dd623-df6d-42a4-bc2c-1a225722f2e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
