<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__nik_akta_pj</name>
   <tag></tag>
   <elementGuidId>ab42acfb-6f63-4e30-8ccf-7f850246d9f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nik_akta_pj']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nik_akta_pj</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2064fcc-1fb9-45af-91b0-512909bfb611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nik_akta_pj</value>
      <webElementGuid>a1f8f416-3878-4e1f-9777-1c052cfcdefe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nik_akta_pj</value>
      <webElementGuid>07a21a3d-9f45-4f55-8c93-55886e8236a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield_34191229</value>
      <webElementGuid>b08bc0b3-f297-42d2-a880-ca2e8963a5a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a301164f-09b6-48d4-8819-1742c9fbc2e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nik_akta_pj&quot;)</value>
      <webElementGuid>2a85e355-9ae5-4c5b-a690-f38a2f24376b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nik_akta_pj']</value>
      <webElementGuid>5728e3c7-35a4-460b-b222-fdc017c83f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section4']/div[3]/div[5]/input</value>
      <webElementGuid>ee7dc97d-ac37-4d86-a42e-4c511514071c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div[5]/input</value>
      <webElementGuid>3852e16a-cad6-4a83-a72a-072735b43c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nik_akta_pj' and @name = 'nik_akta_pj' and @type = 'text']</value>
      <webElementGuid>a3f6f97a-68d4-4fa8-b76b-95d7d8ce5436</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
