<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__no_akta_nikah_pj</name>
   <tag></tag>
   <elementGuidId>ea9a47eb-5fca-4006-95c9-41b2ca9c73fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='no_akta_nikah_pj']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#no_akta_nikah_pj</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed63efae-2936-4e98-a13b-5cf3528b52bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>no_akta_nikah_pj</value>
      <webElementGuid>7dfa899d-14be-4af4-a368-0dcf62b8c292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>no_akta_nikah_pj</value>
      <webElementGuid>bf4d60b8-15fd-4101-acfc-ba9beaea7deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield_34191232</value>
      <webElementGuid>73a1fd6a-8a8c-46c8-a135-077d02e38fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dce49b4e-3f6b-4b70-b8c4-dfd970603fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;no_akta_nikah_pj&quot;)</value>
      <webElementGuid>557f90c7-a678-4f41-84d6-ca56d74ec5e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='no_akta_nikah_pj']</value>
      <webElementGuid>1726b429-5408-491c-bed8-10df0d599a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section4']/div[3]/div[8]/input</value>
      <webElementGuid>32cba5a3-6bbf-4479-aeda-d8c95b0b4198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div[8]/input</value>
      <webElementGuid>1930706a-aab3-4037-9a74-df527fa7548d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'no_akta_nikah_pj' and @name = 'no_akta_nikah_pj' and @type = 'text']</value>
      <webElementGuid>4f126720-6e5c-45f9-94d9-d09c2001a303</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
