<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__siup_iu</name>
   <tag></tag>
   <elementGuidId>aeee6359-3d5a-4129-8c79-a12a826326d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='siup_iu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#siup_iu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da575a7e-1724-4f67-a9ef-8cdb38ce2ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>siup_iu</value>
      <webElementGuid>e68e6356-4979-44a8-b19e-fb300bb60b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>siup_iu</value>
      <webElementGuid>77ab7422-5132-423c-a1dc-da8374aa9e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield_34191245</value>
      <webElementGuid>754f0686-b51e-424b-a158-cb6deea151e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>89a67400-1c2b-477b-aac6-39599db2bd11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;siup_iu&quot;)</value>
      <webElementGuid>a3c5e0c2-21ee-4dd9-bbd8-dad226da7153</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='siup_iu']</value>
      <webElementGuid>f962d8f7-da75-4b03-9be7-aca6ca3603f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section5']/div[3]/div[3]/input</value>
      <webElementGuid>8beca58e-2a45-4dba-ab6a-3f973ed37e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div[3]/input</value>
      <webElementGuid>1a46cf12-504d-491c-bcfd-94d92f7fde04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'siup_iu' and @name = 'siup_iu' and @type = 'text']</value>
      <webElementGuid>cc2ef38b-f871-4a65-bbe5-80085779dfdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
