<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__no_akta_nikah</name>
   <tag></tag>
   <elementGuidId>52202dd8-f6e9-483c-bee7-4398028b260b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='no_akta_nikah']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#no_akta_nikah</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe251039-c408-497a-ae0c-d3039597f9c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>no_akta_nikah</value>
      <webElementGuid>9ff8b373-0b03-4401-b721-defb8bbfc06f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>no_akta_nikah</value>
      <webElementGuid>84697497-5763-4408-8e91-76802054fd69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield_34191210</value>
      <webElementGuid>6fd39d6b-e2a6-436d-a5a3-4570baf33f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84aaaf60-ed2b-4148-a6aa-1036ecbe9a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;no_akta_nikah&quot;)</value>
      <webElementGuid>590d1bb8-5539-41e1-9755-cd96ffcf3422</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='no_akta_nikah']</value>
      <webElementGuid>e1b014a9-0d06-49fd-8702-cc2839aa530e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section3']/div[3]/div[8]/input</value>
      <webElementGuid>52a8a344-ef2b-4f91-8a05-409f0264fb92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>432f0782-5d29-4887-ac4a-1b561803ded4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'no_akta_nikah' and @name = 'no_akta_nikah' and @type = 'text']</value>
      <webElementGuid>ecb56f06-0df5-4032-a48a-5c89dae25380</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
