<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__tdp_nib</name>
   <tag></tag>
   <elementGuidId>46dcd8d3-fdfc-4939-8ce9-17b68a85c3c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tdp_nib']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tdp_nib</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d00cd8f-ffeb-4200-a502-57dd448664f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdp_nib</value>
      <webElementGuid>16b7eebf-ce94-4822-84d1-975b14bb6613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tdp_nib</value>
      <webElementGuid>7f15bf8c-61f1-425d-ab5f-026f0fe87bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield_34191244</value>
      <webElementGuid>ae683396-cb59-42f7-ae38-245c6a31bae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a87acb1e-10ca-4013-918a-08a8f72e68a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tdp_nib&quot;)</value>
      <webElementGuid>19d44e0c-fcfb-4171-b9e5-e59601fab683</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tdp_nib']</value>
      <webElementGuid>2e7bd655-1e49-4740-a7a4-57d3b404a36a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section5']/div[3]/div[2]/input</value>
      <webElementGuid>31d2f352-8fb7-4d01-b550-b11fb599b7df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div[2]/input</value>
      <webElementGuid>0eebe58b-c8b6-4bd8-a2f0-f1660c7edaaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tdp_nib' and @name = 'tdp_nib' and @type = 'text']</value>
      <webElementGuid>67c98ca8-97b0-40d9-aa93-18e456c543c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
