<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__alamat_pj</name>
   <tag></tag>
   <elementGuidId>7724379f-99cd-4132-b788-b580ae6d1243</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='alamat_pj']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#alamat_pj</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7ad36d81-d628-429e-b25a-178d24772e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alamat_pj</value>
      <webElementGuid>7459407e-f007-4e5d-a517-0883c42e278e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>alamat_pj</value>
      <webElementGuid>f09091de-1396-4b12-b281-b5c5bb5ae0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield_34191227</value>
      <webElementGuid>3ffa08a8-9bd9-484c-97dc-4a79ac0de72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>046d33e2-2e55-4bc9-ba00-62684dff150f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alamat_pj&quot;)</value>
      <webElementGuid>185548bd-4900-4018-a085-78e2e2743e40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='alamat_pj']</value>
      <webElementGuid>3cbff290-5604-4686-a897-96d6d701925f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section4']/div[3]/div[3]/input</value>
      <webElementGuid>a7463e48-951d-4d86-8f06-89fb87e8493b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div[3]/input</value>
      <webElementGuid>ced3f484-f839-4a95-97b2-20837b49ad76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'alamat_pj' and @name = 'alamat_pj' and @type = 'text']</value>
      <webElementGuid>77cf2c31-1576-4b2d-8de3-073f0d567137</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
