<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__akta_pendirian</name>
   <tag></tag>
   <elementGuidId>ecda46ee-ad4e-4fa9-9529-123ee60819e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='akta_pendirian']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#akta_pendirian</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9f319c3-2751-4393-8ee1-ef8fe76ff265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>akta_pendirian</value>
      <webElementGuid>4f1a396b-edef-4de9-ad1e-c5102d253d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>akta_pendirian</value>
      <webElementGuid>214d5f55-8812-4ad8-bf64-19f09a549310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield_34191243</value>
      <webElementGuid>24800807-b868-4cf0-9d7f-89f8ca1dae9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d7f0024e-eacf-4895-921b-77a8272f5236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;akta_pendirian&quot;)</value>
      <webElementGuid>ebe5cd22-87e6-4176-8384-1ce8d4480d05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='akta_pendirian']</value>
      <webElementGuid>6b7176f3-98db-418f-a466-9c5a56b8db18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section5']/div[3]/div/input</value>
      <webElementGuid>792327c3-c188-4757-884d-71c602d2db63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div/input</value>
      <webElementGuid>d1136384-b181-43b6-9157-71b3ac7ea7b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'akta_pendirian' and @name = 'akta_pendirian' and @type = 'text']</value>
      <webElementGuid>08098e69-538f-4e3a-90e5-0ba8debf4ae7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
