<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__pekerjaan_pj</name>
   <tag></tag>
   <elementGuidId>2ff4c75b-3d1e-4a11-a4c5-8c63813d5e55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pekerjaan_pj']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pekerjaan_pj</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9ae4068-c6b3-4d7c-a442-018b2995925f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pekerjaan_pj</value>
      <webElementGuid>f0a781c9-d6b7-456f-b100-f856628e279b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pekerjaan_pj</value>
      <webElementGuid>34a4adc4-0fd8-45e8-9c44-77b1c6ae318d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield_34191228</value>
      <webElementGuid>ad5acf74-87d6-4ba5-819e-21cce02a6178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>de1cdb27-a945-4aa8-b85b-4c78b7878060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pekerjaan_pj&quot;)</value>
      <webElementGuid>69a84248-d628-4497-9b3c-e9fca176694f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pekerjaan_pj']</value>
      <webElementGuid>93743fc0-b91d-4022-96e7-868a8fb1c2f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section4']/div[3]/div[4]/input</value>
      <webElementGuid>3be413c7-ee58-4e1a-a721-7585616a1bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div[4]/input</value>
      <webElementGuid>1cefca23-fcc3-4df9-a944-9ab7bbfe0349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pekerjaan_pj' and @name = 'pekerjaan_pj' and @type = 'text']</value>
      <webElementGuid>683b9cb6-1e02-44e3-9c75-a5781c36a697</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
