<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Data_ag_temp_data</name>
   <tag></tag>
   <elementGuidId>8d459f70-6fd7-4ce4-9bc3-0c1edc6bd0a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ag_temp_data']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ag_temp_data</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4c5fe9b-a617-48af-a172-7e96c117407e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ag_temp_data</value>
      <webElementGuid>fc73532b-aec2-44d1-8b69-a6cc24a3f634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ag_temp_data</value>
      <webElementGuid>f5efacf5-cbd8-4b76-b801-875cceb91daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield_34195954</value>
      <webElementGuid>6c057588-9661-45e2-ab0e-a2ea19d1b9b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>25d3d7d0-56bf-4d45-8409-c2f47387f9d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ag_temp_data&quot;)</value>
      <webElementGuid>790c877b-63fc-4888-a7ff-843603824ecc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ag_temp_data']</value>
      <webElementGuid>90d1fb5a-2156-4b58-9d83-6444f254e720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coldat_adgrid_34195901']/div[3]/input</value>
      <webElementGuid>99eefaa7-8828-4065-a921-496cf061b01b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[3]/input</value>
      <webElementGuid>dde0a4fd-e15f-40b8-8af2-5d14f98db0da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ag_temp_data' and @name = 'ag_temp_data' and @type = 'text']</value>
      <webElementGuid>988516ad-b127-49c9-9d8c-038e4cb026f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coldat_adgrid_34191251']/div[3]/input</value>
      <webElementGuid>0cc90f92-4578-422a-b716-fce17143372c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
