<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__status_pj</name>
   <tag></tag>
   <elementGuidId>6419c6e5-06d4-474d-a971-0b7809ce06f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='status_pj']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#status_pj</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>970eea51-1f33-4a01-86f6-a871ac0d83b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>status_pj</value>
      <webElementGuid>1715108d-c2e0-4ddf-96ec-22adb6153720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status_pj</value>
      <webElementGuid>e18ff966-c30f-4a13-af4c-001b752e697e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield_34191230</value>
      <webElementGuid>153ad57b-72bd-4246-8e20-c785538bb14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8389ac4c-6cb5-4ed9-8ae7-b57e31f5b19f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;status_pj&quot;)</value>
      <webElementGuid>d3f986dc-40bf-47f2-9d03-829c9ec52937</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='status_pj']</value>
      <webElementGuid>ef636301-2e19-4556-a23e-936236e10645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section4']/div[3]/div[6]/input</value>
      <webElementGuid>48c1f212-308a-4582-818c-6503e2d2e590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div[6]/input</value>
      <webElementGuid>de258369-93e3-4bdb-b2ce-09bedd1198a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'status_pj' and @name = 'status_pj' and @type = 'text']</value>
      <webElementGuid>2fe9f71d-8214-4439-9e30-962d033ed68c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
