<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__npwp_iu</name>
   <tag></tag>
   <elementGuidId>9f61e897-51ee-4098-ac46-eb097b1c7dc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='npwp_iu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#npwp_iu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c785343a-353b-4215-aa1e-73ef7cabf025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>npwp_iu</value>
      <webElementGuid>8c347f70-e032-48b0-817a-a61393ff5762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>npwp_iu</value>
      <webElementGuid>b5e085cb-1365-4049-9fdf-42be232cb061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield_34191247</value>
      <webElementGuid>087a2c35-0694-4b3d-bac6-da375a17cd63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>89b59866-3e4d-49f2-b985-c2ec62f962e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;npwp_iu&quot;)</value>
      <webElementGuid>94942ea9-8ec1-44bb-baad-bd5480e2c722</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='npwp_iu']</value>
      <webElementGuid>37ea941a-d8cc-4d94-985e-59b3a929690c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section5']/div[3]/div[5]/input</value>
      <webElementGuid>21979a86-178d-4dd1-a87d-9a17b44dc7e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div[5]/input</value>
      <webElementGuid>8c0be14d-11d7-4377-a239-0ea6d062508f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'npwp_iu' and @name = 'npwp_iu' and @type = 'text']</value>
      <webElementGuid>c9d56994-a43f-4b52-a355-8cde6ead59fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
