<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add</name>
   <tag></tag>
   <elementGuidId>85bd7075-583e-4521-b70a-e2e65a82002d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='coldat_adgrid_34195901']/div/div[3]/div/span/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ui-button-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ce2d74de-f1c7-4b8b-8d1b-00babf2eb5ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text</value>
      <webElementGuid>01c6c755-200d-4f82-8b2b-023d56ad6f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>9bcf2d76-5737-496f-9ca1-bab55f79f483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coldat_adgrid_34195901&quot;)/div[@class=&quot;pq_grid pq-grid ui-widget ui-widget-content ui-corner-all&quot;]/div[@class=&quot;pq-grid-bottom ui-corner-bottom&quot;]/div[@class=&quot;pq-grid-toolbar&quot;]/span[@class=&quot;ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-primary&quot;]/span[@class=&quot;ui-button-text&quot;]</value>
      <webElementGuid>19f0433b-7e0b-4443-b1df-7f9b80d4237c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coldat_adgrid_34195901']/div/div[3]/div/span/span[2]</value>
      <webElementGuid>5a704227-0c41-4882-a6be-d76dcab0acd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::span[2]</value>
      <webElementGuid>ddbddbfd-3315-4ed5-98e8-37f59033b4e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page'])[1]/preceding::span[9]</value>
      <webElementGuid>23a939b9-ece3-4c5f-a992-8eef59aee75b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>63dd5253-448f-4973-8c3d-9f587a2b1a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span[2]</value>
      <webElementGuid>955b8882-4478-4abe-b86e-ebb7acfa8e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>4a6aa545-c264-430b-ad3b-943523f30262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coldat_adgrid_34191251']/div/div[3]/div/span/span[2]</value>
      <webElementGuid>187eb84d-0e60-423f-a4c0-e671d4cdb6b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
