<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__nama_ibu_deb</name>
   <tag></tag>
   <elementGuidId>844dd163-141a-498e-bb0c-2c44261ec34b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nama_ibu_deb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nama_ibu_deb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a05c39b-a19f-4ce1-977f-dec85cd7afad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_ibu_deb</value>
      <webElementGuid>7fb6ab1e-e60d-4b17-8fa8-3098de59be63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama_ibu_deb</value>
      <webElementGuid>f6eea86e-d9db-413b-a389-aa9b18889028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm alphabet_input</value>
      <webElementGuid>f5e3a7a7-e3da-4e34-95cb-22ab51c59038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>95c20560-cb89-41d5-addb-ec562800355b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nama_ibu_deb&quot;)</value>
      <webElementGuid>9303efbf-092c-4a67-a443-f0d7f47b13cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nama_ibu_deb']</value>
      <webElementGuid>95a7bb35-24ec-42e0-ba90-09acb7875b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_nama_ibu_deb']/input</value>
      <webElementGuid>c4ccb2fe-1211-4568-b34d-efbf88d48640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/input</value>
      <webElementGuid>0c57648c-0744-4b20-b833-82328586c37a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nama_ibu_deb' and @id = 'nama_ibu_deb' and @type = 'text']</value>
      <webElementGuid>0e095659-c337-4a50-8c18-b40bc126dd05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
