<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__npwp</name>
   <tag></tag>
   <elementGuidId>d365fc01-e26b-403f-9614-452ab1b90cf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#npwp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='npwp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1adb98c3-2f6e-4abb-a5f9-9eae18f58c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c23f288-6863-41c4-aceb-abf7ca6140f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>npwp</value>
      <webElementGuid>69961111-27fd-4f89-9cec-39a71117fb57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>npwp</value>
      <webElementGuid>b42fed16-5be5-40ab-a048-af4ea56b86f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm number_input</value>
      <webElementGuid>3f9d9090-118f-4a55-bcbd-fad397c28693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>2511bf5a-437f-43ad-a71c-5c144a798d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;npwp&quot;)</value>
      <webElementGuid>76af45b8-5bbb-4282-bd4b-8dd793f3e76a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='npwp']</value>
      <webElementGuid>669a7ca4-76e5-4cf6-935a-cfb7eba9a34d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_identitas_debitur']/div[13]/input</value>
      <webElementGuid>7b878a9a-7632-4707-b20c-16f788e8a625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/input</value>
      <webElementGuid>1adb1515-a7fd-4f1c-8b30-6274bd9c1c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'npwp' and @name = 'npwp']</value>
      <webElementGuid>539584a8-4fa0-4fea-9542-4749d745eab2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
