<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Individu  Perorangan_nik_akta_dhnbi</name>
   <tag></tag>
   <elementGuidId>953d972d-3fc7-4ba5-80c5-d7d2f5fc52ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nik_akta_dhnbi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nik_akta_dhnbi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88f39756-4cd1-4df6-b77b-43473e818bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b22b5ace-dcfd-4537-84b4-8c029567d7cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nik_akta_dhnbi</value>
      <webElementGuid>16af7bb4-5ded-45bf-b773-daa02adda5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nik_akta_dhnbi</value>
      <webElementGuid>e71ea737-3ee3-463a-9e28-1ec817cee145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control number_input</value>
      <webElementGuid>a5ef07eb-7524-4531-a158-b77eb782ec20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Check NIK</value>
      <webElementGuid>4103d56a-44cc-4580-9dc1-c43520fa2634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>f8fcdd4e-7111-4baa-9932-2e9a872a52ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nik_akta_dhnbi&quot;)</value>
      <webElementGuid>73c14b42-26f7-4582-ac87-a9ebcf3ed629</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nik_akta_dhnbi']</value>
      <webElementGuid>5c21f36e-65bd-4829-924e-83388a00b1ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_check_dhnbi']/div/div/div/input</value>
      <webElementGuid>e1125925-1ec3-4382-a667-0324c1610b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>eb25f70e-2369-4e43-86ac-ed5e4a2613e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nik_akta_dhnbi' and @name = 'nik_akta_dhnbi' and @placeholder = 'Check NIK']</value>
      <webElementGuid>81ac1288-6002-4b0e-a467-9e7835e9d670</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
