<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__debitur_phone_number</name>
   <tag></tag>
   <elementGuidId>3f245d26-e64d-43fe-814d-7b12bf880439</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#debitur_phone_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='debitur_phone_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b024ddc-83cb-491d-a788-2a6aa319119d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c5a039db-d007-4f0f-8ec6-3bd98d47cfc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>debitur_phone_number</value>
      <webElementGuid>c74cd88f-d202-4524-a918-4c5805eaa467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>debitur_phone_number</value>
      <webElementGuid>8c745384-90a1-43a2-b347-cdd9d767d368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm phone_number_class number_input</value>
      <webElementGuid>b0dc6deb-6ac0-4577-a65e-d14d27e4ece7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;debitur_phone_number&quot;)</value>
      <webElementGuid>a19f2767-614e-4fcc-a22e-77a7bee49b0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='debitur_phone_number']</value>
      <webElementGuid>a51d665a-157f-4197-91d3-6c2301cd68db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_phone_number']/div/div/input</value>
      <webElementGuid>0ef32733-cab9-434c-827a-60f482ffd38e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/div/input</value>
      <webElementGuid>a863d346-07e0-443a-8260-b165b08f82ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'debitur_phone_number' and @name = 'debitur_phone_number']</value>
      <webElementGuid>a9d4a6ed-ce53-4381-8b20-0ff981dbd160</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
