<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__kota_deb</name>
   <tag></tag>
   <elementGuidId>99456af5-6155-4f42-ad8b-b4845afb94dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kota_deb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kota_deb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5bb78689-064b-4ed9-a792-0a34a741499e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kota_deb</value>
      <webElementGuid>3c8b73ad-5a36-41bd-b011-9277f746753c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kota_deb</value>
      <webElementGuid>f2664838-5a15-4b1e-9524-1b8bd48b8ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm alphabet_input</value>
      <webElementGuid>92d26116-89c8-4cfe-8067-1a8568e6964b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3398c172-f594-4071-9394-2bd53a5bb6d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kota_deb&quot;)</value>
      <webElementGuid>cf3d5eb8-fcbf-4fed-872d-c8e6355e0e63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kota_deb']</value>
      <webElementGuid>e21a1301-3f7a-46fa-9fd2-29090f40e2a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_identitas_debitur']/div[11]/input</value>
      <webElementGuid>d32044ce-9b38-423e-8ecb-75970ea06c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/input</value>
      <webElementGuid>8e012808-8b31-4dad-9d4c-e214ddfa8bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'kota_deb' and @id = 'kota_deb' and @type = 'text']</value>
      <webElementGuid>90adf134-bb72-4255-9903-d7d2eb012262</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
