<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__tgl_lahir_akta</name>
   <tag></tag>
   <elementGuidId>97ac7fa7-283d-4167-893b-97b9973e3aa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tgl_lahir_akta</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tgl_lahir_akta']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66183454-cca2-474e-b6a4-2d88e9229ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d4d7d1a9-079c-4776-816a-da079a322dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tgl_lahir_akta</value>
      <webElementGuid>8a36a897-a9bb-49d2-8f0f-9de6724cc30c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tgl_lahir_akta</value>
      <webElementGuid>300f6956-0233-430f-b185-e318285c3948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>72ddfa41-ef3c-427e-8cae-51878465e658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-inputmask-alias</name>
      <type>Main</type>
      <value>datetime</value>
      <webElementGuid>f6e31a65-0b07-441b-9350-eefb566b92f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-inputmask-inputformat</name>
      <type>Main</type>
      <value>dd-mm-yyyy</value>
      <webElementGuid>72f11d53-6815-43fb-a217-a085f5355254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-inputmask-placeholder</name>
      <type>Main</type>
      <value>dd-mm-yyyy</value>
      <webElementGuid>90d930af-4e65-44bc-87c8-e79b4550422c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd-mm-yyyy</value>
      <webElementGuid>35be3e15-f33e-4f71-963e-dff2ae928b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>0b58ba42-605a-4ca9-9124-cce2a7cccd68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tgl_lahir_akta&quot;)</value>
      <webElementGuid>2db702d0-8404-4d7e-9132-81736d0a9b49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tgl_lahir_akta']</value>
      <webElementGuid>2d2af053-c56f-44f7-89f0-e286e8bd0243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_identitas_debitur']/div[15]/div/input</value>
      <webElementGuid>484df1b6-ff0a-4dc7-8f65-ba5fbffe375c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/input</value>
      <webElementGuid>ad6d8f79-83fe-45ee-a6cd-56c3ccf16bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tgl_lahir_akta' and @name = 'tgl_lahir_akta' and @placeholder = 'dd-mm-yyyy']</value>
      <webElementGuid>ba6a617f-e32c-4d26-bbe1-89f69cfb5b73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
