<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__tempat_lahir</name>
   <tag></tag>
   <elementGuidId>a92c5fdf-73a2-49c3-83df-7d1c861ca1ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tempat_lahir</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tempat_lahir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46247e7d-642d-4562-b13b-d1cee7785853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d0fb0aea-4540-43b8-b77e-9cb236b08f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tempat_lahir</value>
      <webElementGuid>3cf24a14-a029-4fef-b2f4-9c4f9da35f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tempat_lahir</value>
      <webElementGuid>e9309c8a-d0de-4e8c-b939-7d93cf24c86f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm alphabet_input</value>
      <webElementGuid>7507e88a-7d60-46a2-bb22-0491364ec508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempat_lahir&quot;)</value>
      <webElementGuid>abec561f-c23a-42fa-98d3-e56cabb100d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tempat_lahir']</value>
      <webElementGuid>4c80ad59-e5f1-495f-82e0-889480b537d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_identitas_debitur']/div[16]/input</value>
      <webElementGuid>f8714e08-28ea-4444-a5ad-33640443738b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/input</value>
      <webElementGuid>2c336d36-b5e5-40c7-b140-ba1b742fa44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tempat_lahir' and @name = 'tempat_lahir']</value>
      <webElementGuid>cd136e0e-8b24-42a9-a020-293ed85916a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
