<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__kode_pos_deb</name>
   <tag></tag>
   <elementGuidId>c19f9507-8834-4d35-a9df-5940c99143b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kode_pos_deb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kode_pos_deb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36b56e7f-bb07-4537-a065-577aca25f06b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kode_pos_deb</value>
      <webElementGuid>ae1481b0-bb0a-4742-91ff-04bb06768b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kode_pos_deb</value>
      <webElementGuid>ea7bf3e8-f01a-4528-a836-4a6ed58c43dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm number_input</value>
      <webElementGuid>ea04062e-0e59-4479-98c2-c2e174c2893a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b15f0a9f-91b5-4757-8f07-14a787ddd748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>25003d3f-f949-4cac-a80e-b6555f18a711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kode_pos_deb&quot;)</value>
      <webElementGuid>7bea34a3-3c39-4903-b06a-f8d35b27a8c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kode_pos_deb']</value>
      <webElementGuid>691d92ab-ff5c-473c-a822-9d6e896360a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_identitas_debitur']/div[12]/input</value>
      <webElementGuid>bedee42a-c02a-4347-9591-70054a21eddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/input</value>
      <webElementGuid>211e80f0-c027-40e0-8ab5-1921fc704c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'kode_pos_deb' and @id = 'kode_pos_deb' and @type = 'text']</value>
      <webElementGuid>708d3c3a-4b6b-4dde-bf7c-8dfec0cfd540</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
