<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Tunai</name>
   <tag></tag>
   <elementGuidId>d502618c-5f2a-41a0-ba4e-ffedf6edb9a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form_agunan']/div/div/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>564939c5-8985-458e-ad2b-a8d6fb788b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>checkboxPrimary2</value>
      <webElementGuid>ec663ac2-1a2d-4c15-b1cc-22adce5c9977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tunai</value>
      <webElementGuid>e10de182-41f4-45ac-96cb-5923227e4c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_agunan&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;p-2 border rounded column-checker&quot;]/div[@class=&quot;icheck-primary&quot;]/label[1]</value>
      <webElementGuid>db29abe8-9e0f-41eb-8bf1-11af3dff739e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_agunan']/div/div/div[2]/label</value>
      <webElementGuid>a6ac7015-175e-4ad8-a4c3-d86fb752099f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fixed Asset'])[1]/following::label[1]</value>
      <webElementGuid>c5805f10-bd79-40b6-ab3c-f22e50e12ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Agunan'])[1]/following::label[2]</value>
      <webElementGuid>7f920f62-9020-4cde-911a-7f10a0fd2112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back To Back'])[1]/preceding::label[1]</value>
      <webElementGuid>6353d6ee-64e4-4774-b00a-c6dd62556b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penjamin Deposito'])[1]/preceding::label[2]</value>
      <webElementGuid>01b1d6fe-9045-4b33-b01e-b833ba4317b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tunai']/parent::*</value>
      <webElementGuid>1ea55880-51ab-4b53-ab93-922a856ccf9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/form/div/div/div[2]/label</value>
      <webElementGuid>e0e70d6c-3795-4c18-8a5b-12148fd77f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Tunai' or . = 'Tunai')]</value>
      <webElementGuid>652c31d1-05e2-4d1c-9d5d-21bc7f38f9af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
