<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-- Pilih --</name>
   <tag></tag>
   <elementGuidId>95bfd564-bfd1-4609-a5af-2ff137fa74f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-sektor_ekonomi-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-sektor_ekonomi-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>797ee41e-c5ef-4b66-ae94-284e8b739f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>a3de0609-39f2-4dbd-8990-e083109898c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-sektor_ekonomi-container</value>
      <webElementGuid>0c298e30-a9e7-493e-840d-d8f48d9f5373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>922a9c80-d22a-4e0b-be58-265acbabe6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>34e4cc5c-2ff4-44ad-968d-2adbaa6b55e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> -- Pilih -- </value>
      <webElementGuid>fb7ccd3e-a95f-4dda-81a4-4e98dda37279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> -- Pilih -- </value>
      <webElementGuid>523ff0b7-197b-4b94-b68c-5287fec722e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-sektor_ekonomi-container&quot;)</value>
      <webElementGuid>d9b1ede6-83a1-4b2f-8689-7a2c3419f3d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-sektor_ekonomi-container']</value>
      <webElementGuid>f50232f7-2a15-4f75-b80d-bc2e7242f451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_identitas_debitur']/div[21]/span/span/span/span</value>
      <webElementGuid>63c43b8c-c364-48f4-93fc-5d4fbf383118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[15]/following::span[4]</value>
      <webElementGuid>b1d07017-b69e-4b2d-9e35-3e794d6a1ae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[16]/preceding::span[3]</value>
      <webElementGuid>82c6a4f7-7fa2-48d2-995b-8f1bff94e980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/span/span/span/span</value>
      <webElementGuid>3485ff25-8da6-4d96-94fb-b933eaa29d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-sektor_ekonomi-container' and @title = ' -- Pilih -- ' and (text() = ' -- Pilih -- ' or . = ' -- Pilih -- ')]</value>
      <webElementGuid>b57a1917-4c50-4ced-97b1-664efdbcfacf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-jenis_kredit-container']</value>
      <webElementGuid>355f6e7a-78dd-46a1-8514-99efc7d722e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_identitas_debitur']/div[20]/span/span/span/span</value>
      <webElementGuid>b799f7cc-2a5c-43ca-bd2e-b03fcbf26265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[14]/following::span[4]</value>
      <webElementGuid>2a533778-3aeb-4c8f-b45c-28b6e328de2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[15]/preceding::span[3]</value>
      <webElementGuid>1650dd1b-ed99-404e-bcbe-230e32199e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/span/span/span/span</value>
      <webElementGuid>7591f1f4-b805-482e-8b6f-6ceba0114ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-jenis_kredit-container' and @title = ' -- Pilih -- ' and (text() = ' -- Pilih -- ' or . = ' -- Pilih -- ')]</value>
      <webElementGuid>210eea3a-7418-4c91-bbdb-aaded2ba25f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-jenis_kelamin-container']</value>
      <webElementGuid>cc8428c3-3dfb-46bc-87fa-3eee37ccad5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_jenis_kelamin']/span/span/span/span</value>
      <webElementGuid>e456f222-ddff-47ae-a0cf-4c0879749014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::span[4]</value>
      <webElementGuid>34c5c25c-eb38-49b3-80de-fa33ae46b230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::span[3]</value>
      <webElementGuid>886f9bd4-82e4-42eb-81aa-4c79ecfc5a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>afe66dea-3a9c-4d6c-bd67-edc47a270d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-jenis_kelamin-container' and @title = ' -- Pilih -- ' and (text() = ' -- Pilih -- ' or . = ' -- Pilih -- ')]</value>
      <webElementGuid>a828a859-5f4c-48a6-81c3-e33d2f41af33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
