<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Catatan Pengajuan_catatan_crm</name>
   <tag></tag>
   <elementGuidId>7fdfb901-277d-44d1-ad53-50e815249506</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#catatan_crm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='catatan_crm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>03be9a08-ee6c-4d46-8526-f96070ed29bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>catatan_crm</value>
      <webElementGuid>9ea346c6-7d57-4c6a-bd68-f399c6d20276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>catatan_crm</value>
      <webElementGuid>48184205-2a95-4e9f-a69b-ff5a5c1b99f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>6882d60e-2599-4c60-a1ed-e7d330898ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>781ca055-1210-4841-bfb4-173eefedd97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;catatan_crm&quot;)</value>
      <webElementGuid>dc66d531-26b3-41e0-b0a6-26e2e3941f52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='catatan_crm']</value>
      <webElementGuid>e5a4de80-e4ea-443a-9f5e-a954445e8c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_identitas_debitur']/div[27]/div/textarea</value>
      <webElementGuid>a863f95b-7e09-47b3-bdad-db31a6af9507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div/textarea</value>
      <webElementGuid>64112315-5a76-4d17-abf5-53bef6acc500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'catatan_crm' and @id = 'catatan_crm']</value>
      <webElementGuid>a9a46ab2-489e-42e4-9d92-26c54b1b73da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
