<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Span Jenis Kred</name>
   <tag></tag>
   <elementGuidId>0615d25f-f10d-4f9f-93fe-e4b59bfc9cae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-jenis_kredit-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-jenis_kredit-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9a4988f5-b250-4e83-ad37-32014e654ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>e9d581bc-e81e-4c9d-847b-73c90eb20411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-jenis_kredit-container</value>
      <webElementGuid>b759d30a-a8a4-4e9f-a985-6dfed2958ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>9d33f60a-e812-4e4f-8349-7adfe072d0f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1f26ab6c-e53f-4c72-9e83-392883fe2c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> -- Pilih -- </value>
      <webElementGuid>f8412224-7210-4ca7-a380-8c3f79fa86aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> -- Pilih -- </value>
      <webElementGuid>aa8e24d1-f980-4aa4-a153-a70180f4fc1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-jenis_kredit-container&quot;)</value>
      <webElementGuid>de9ffc34-436b-4ac6-81b9-3f9dceb8d5da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-jenis_kredit-container']</value>
      <webElementGuid>11bf1684-c603-4a71-b631-0619fb4caf55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_identitas_debitur']/div[20]/span/span/span/span</value>
      <webElementGuid>953648aa-57c6-45fa-aa1e-11d85c9e7862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[14]/following::span[4]</value>
      <webElementGuid>861388a2-c9ac-4ea5-955c-535439deed23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[15]/preceding::span[3]</value>
      <webElementGuid>c89d6c35-7283-42e7-a308-60d617b737d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/span/span/span/span</value>
      <webElementGuid>60fbd36d-c565-47d8-8f2f-ca2dd35c4a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-jenis_kredit-container' and @title = ' -- Pilih -- ' and (text() = ' -- Pilih -- ' or . = ' -- Pilih -- ')]</value>
      <webElementGuid>c874ab7f-4fa1-446c-a64d-fba3955dcf8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
