<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Laki - Laki</name>
   <tag></tag>
   <elementGuidId>024e33ee-b079-41fa-98cc-8090d6a8ce28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-jenis_kelamin-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-jenis_kelamin-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a7ec61de-abb4-4aa9-828f-88c4edcbcc49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>9eba0f12-4291-4206-b0eb-6916f6df8619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-jenis_kelamin-container</value>
      <webElementGuid>2104f758-b14b-4142-b715-b4b57c9d9317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>53cb88ba-200a-4a95-a143-19cfcecb7dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8bbb815a-e9fa-4b3d-b370-f87f4a0c3eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> Laki - Laki </value>
      <webElementGuid>3d0085fa-9e4a-4b6c-a1b5-2a95e0c4643c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Laki - Laki </value>
      <webElementGuid>2304a4b8-2dc6-4076-af6c-937498d10d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-jenis_kelamin-container&quot;)</value>
      <webElementGuid>6a46116a-4e74-4855-833c-379f28dcb39c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-jenis_kelamin-container']</value>
      <webElementGuid>359e475d-c183-4023-a34e-21331c722949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_jenis_kelamin']/span/span/span/span</value>
      <webElementGuid>abefe327-a3b0-4037-9280-2bfd83f069b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::span[4]</value>
      <webElementGuid>7fec0bc5-72fd-4135-a9d6-b2944e37eaed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::span[3]</value>
      <webElementGuid>d8a52f94-7c3b-4c28-810f-cedccf3e42c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>9194e88c-1f68-4fac-9c8d-1af186217e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-jenis_kelamin-container' and @title = ' Laki - Laki ' and (text() = ' Laki - Laki ' or . = ' Laki - Laki ')]</value>
      <webElementGuid>0f4b33ad-bf99-4525-b604-54f17650fb4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
